### PR TITLE
fix for apikey #527

### PR DESCRIPTION
**Pull request by dreamgeekcoder**
https://github.com/SocialiteProviders/Providers/issues/527 fix.. hope i did this right :)

### CODE REVIEW

**Comment by atymic** [comment]
cc @sofwar @ilumos could you check this? Know you guys are using this provider.
Also see https://github.com/SocialiteProviders/Providers/issues/527

**Review by sofwar — CHANGES_REQUESTED** [review]
I think the "client_secret" in the "additionalConfigKeys" function is superfluous. Looks good though! https://github.com/SocialiteProviders/Manager/blob/b5c2a9bd16955e228fca950e08dccce8f6a26e66/src/Helpers/ConfigRetriever.php#L49

**Comment by atymic** [comment]
@sofwar would this not be a breaking change due to the name of the config option changing?
I think we just need to update the docs to tell you to use the `api_key` config, right?

**Comment by dreamgeekcoder** [comment]
I know i tried several previous roll back versions of this code and one socialite/manager required that either a client_secret and/or client_id was present and gave errors if it didn't have both...  api_key was not an acceptable response

It looks like its not required in the new version of the manager.. .but I figured putting it back to the way that every other one is on here was made more sense. Either way.. 👍

**Comment by sofwar** [comment]
> @sofwar would this not be a breaking change due to the name of the config option changing?
> I think we just need to update the docs to tell you to use the `api_key` config, right?

@atymic  I propose to use the default old value for backward compatibility 
`$this->getConfig('client_secret', $this->getConfig('api_key'))`

**Comment by atymic** [comment]
> > @sofwar would this not be a breaking change due to the name of the config option changing?
> > I think we just need to update the docs to tell you to use the `api_key` config, right?
> 
> @atymic I propose to use the default old value for backward compatibility
> `$this->getConfig('client_secret', $this->getConfig('api_key'))`

That sounds perfect to me :) @dreamgeekcoder could you make that change?

**Comment by atymic** [comment]
Please PR on the main providers repo.
https://github.com/SocialiteProviders/Providers

**Pull request closed without merging**
